### ISSUE TITLE
MDA1 grades

### ISSUE THREAD

**Issue by asfarlathif** [stat545ubc-2023/mda-Fanny-Dupont#1]
Hi Fanny,

In Exercise 1.2, you should try to use `tidyverse` functions to get the attributes like `ncol()` and ` nrow()` which `glimpse()` will do (-1)

ALso, for M2, i would recommend adding README file with each subdirectories in your repo (like Milestone 1)

35/36

great job!

**Comment by Fanny-Dupont** [comment]
Thanks :)
